# Change these first
owner: sachingodishela # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sachin Godishela
    url: https://api.sachingodishela.com
    headers:
      - "User-Agent: Upptime/sachingodishela"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sachingodishela.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sachin Godishela Status
  introTitle: "**Sachin Godishela**'s blog, art gallery, tools and more,"
  introMessage: This is a  status page which uses **real-time** data from my [GitHub repository](https://github.com/sachingodishela/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
